### ISSUE TITLE
Project Requirements

### ISSUE THREAD

**Issue by hzzyy1997** [nyu-software-engineering/fall-2019-easy-nyu#1]
## Estimate of effort
M
## Acceptance criteria
- [x] Come up with stakeholder interviews questions
- [x] Draft and send email to Prof and Tutor requesting interviews
- [x] Interview 1
- [x] Interview 2
- [x] End-user observation
- [x] Use Cases 
- [x] Domain modeling
- [x] README.md 
- [x] CONTRIBUTING.md

**Comment by XuanzhengLin** [comment]
We should be able to get those done by one week ... which we are supposed to get it done as an assignment due in 10/2.

**Comment by XuanzhengLin** [comment]
I write this in the user story format so that it can be linked to the task board.

**Comment by hzzyy1997** [comment]
We should still have it to keep track of the progression of our Requirements

**Comment by XuanzhengLin** [comment]
Finished.
