### ISSUE TITLE
Add React Router

### ISSUE THREAD

**Issue by hzzyy1997** [nyu-software-engineering/fall-2019-easy-nyu#110]
## Estimation of work
- L

## Acceptance criteria
- [ ] Hide forum submission URLs
- [x] Show clean customized URLs
- [x] Hide and Show components on the page to achieve redirect with one page

**Comment by mstillman9** [comment]
I'm pretty sure this is done.

**Comment by mstillman9** [comment]
Closed per discussion on slack.
