### ISSUE TITLE
Incorporate the type of prof field in course object

### ISSUE THREAD

**Issue by XuanzhengLin** [nyu-software-engineering/fall-2019-easy-nyu#112]
Related to User Story #57 

## Acceptance criteria
- [x] Modify the prof field from a string to be a list of prof objects
- [x] Pass unit test

**Comment by mstillman9** [comment]
Done in PR #111 and superseded by Issue #128.

**Comment by XuanzhengLin** [comment]
Yes this is done by PR #111.  The issue #128 is the additional step to connect front end with back end.
