### ISSUE TITLE
Watch Youtube tutorials about GraphQL

### ISSUE THREAD

**Issue by XuanzhengLin** [nyu-software-engineering/fall-2019-easy-nyu#12]
Acceptance Criteria
- [ ] Watch [GraphQL Youtube Tutorial](https://www.youtube.com/watch?v=7giZGFDGnkc&t=122s)

**Comment by hzzyy1997** [comment]
It is Spike because it is not related to any user stories

**Comment by XuanzhengLin** [comment]
Closed because we are now using REST.
