### ISSUE TITLE
Install packages for development

### ISSUE THREAD

**Issue by XuanzhengLin** [nyu-software-engineering/fall-2019-easy-nyu#13]
Acceptance Criteria
- [x] npm
- [x] mongoose
- [x] express
- [x] graphql
- [x] nodemon
- [x] express
- [x] express-graphql

**Comment by hzzyy1997** [comment]
It is Spike because it is not related to any user stories

**Comment by hzzyy1997** [comment]
Note: For developer tools like nodemon, node, mocha, and eslint, please do not install as production dependency. Use install --dev to install, so that when the application is deployed, the developer tools will not be installed on the cloud server.
