### ISSUE TITLE
Include Use Cases in REQUIREMENTS.md

### ISSUE THREAD

**Issue by XuanzhengLin** [nyu-software-engineering/fall-2019-easy-nyu#14]

**Comment by bloombar** [comment]
@nyu-software-engineering/fall-2019-easy-nyu - this is a Spike, not a task, since it has no user story associated with it.

**Comment by XuanzhengLin** [comment]
Hi Prof @bloombar  I understand the reason why you want to assign this issue as a spike. However, this issue is a sub-task that constitutes the acceptance criteria of issue #8, which was why it was originally labelled as a task.
