### ISSUE TITLE
Public Prof Search

### ISSUE THREAD

**Issue by XuanzhengLin** [nyu-software-engineering/fall-2019-easy-nyu#142]
Related to User Story #74 

## Acceptance criteria
- [ ] Implement a re-direct button on the front page for prof search
- [ ] Render prof after sorting from most to least comments in get request
- [ ] Pass unit test

**Comment by mstillman9** [comment]
Superseded by #137. Done.

**Comment by XuanzhengLin** [comment]
This should be regarded because we went for a different visual display. I am gonna remove it from the task board.
