### ISSUE TITLE
Data Scraper to get professor and course info

### ISSUE THREAD

**Issue by hzzyy1997** [nyu-software-engineering/fall-2019-easy-nyu#148]
## Estimation of work
- 13

## Acceptance criteria
- [x] Data Scrapper to obtain all professor information from NYU website
- [x] Modify the MongoDB Models to fit data scraped from NYU website
- [x] Inject Data into MongoDB

**Comment by XuanzhengLin** [comment]
This should be the biggest task for Sp 3.

**Comment by XuanzhengLin** [comment]
Done by Jack!
