### ISSUE TITLE
Display comments in Prof Profile

### ISSUE THREAD

**Issue by XuanzhengLin** [nyu-software-engineering/fall-2019-easy-nyu#162]
Related to User Story #74
### Estimation of work
- 5

### Acceptance criteria
- [ ] Display comments for a prof profile in React
- [ ] Pass unit test

**Comment by mstillman9** [comment]
Done in #181

**Comment by XuanzhengLin** [comment]
For prof with id: 5ddb5c3757629f5a03e677c1, her comment is not properly rendered. Need to fix backend.

**Comment by mstillman9** [comment]
Wrong issue. That issue is #182, not this one.
