### ISSUE TITLE
Display Courses in React

### ISSUE THREAD

**Issue by XuanzhengLin** [nyu-software-engineering/fall-2019-easy-nyu#69]
Related to User Story #57 

## Acceptance criteria
- [x] Write React.js code to display courses
- [x] Pass unit test

**Comment by XuanzhengLin** [comment]
@mstillman9 Please make sure of the code can be run and conducted testing on your own. Thus, I move this task to Sprint 2 to do.

**Comment by mstillman9** [comment]
With PR #124 merged, this task is complete.
