### ISSUE TITLE
Backend code to comment on the Prof

### ISSUE THREAD

**Issue by XuanzhengLin** [nyu-software-engineering/fall-2019-easy-nyu#78]
Related to User Story #74 

### Acceptance Criteria
- [x] Get Request
- [x] Post Request
- [x] Pass unit test

**Comment by mstillman9** [comment]
I'm pretty sure this is a duplicate of #114

**Comment by XuanzhengLin** [comment]
It was not a dup. I made updates to the whole previous comment method.

**Comment by mstillman9** [comment]
Oh, okay, I didn't see any PRs mentioning this task.

**Comment by XuanzhengLin** [comment]
No worries bro. Previous comment was very superficial. Thanks for keeping an eye on the code.
