### ISSUE TITLE
As a member of the development team, I want to have the basic web backbone setup, so that I can add and work on new features.

### ISSUE THREAD

**Issue by XuanzhengLin** [nyu-software-engineering/fall-2019-easy-nyu#9]
### Acceptance Criteria
- [ ] Each developer is granted accesses to MongoDB
- [ ] Server is running on local host

**Comment by hzzyy1997** [comment]
This should be a Spike because it is not related to project user stories

**Comment by XuanzhengLin** [comment]
This is taken care of by #18. Please Ignore.
